name: atomic-sway
description: Fedora Atomic Sway with extras

base-image: quay.io/fedora-ostree-desktops/sericea
image-version: 40

modules:
  - type: rpm-ostree
    repos:
      - https://download.docker.com/linux/fedora/docker-ce.repo
      - https://copr.fedorainfracloud.org/coprs/aquacash5/nerd-fonts/repo/fedora-%OS_VERSION%/aquacash5-nerd-fonts-fedora-%OS_VERSION%.repo
    install:
      - zsh
      - neovim
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
      - power-profiles-daemon
      
  - type: default-flatpaks
    notify: true
    system:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      repo-title: "Flathub (system-wide)"
      install:
        - com.brave.Browser
        - com.borgbase.Vorta
        - com.jetbrains.IntelliJ-IDEA-Ultimate
        - com.plexamp.Plexamp
        - org.kde.dolphin
        - org.kde.gwenview
        - org.kde.kalk
        - org.kde.kate
        - org.kde.konsole
        - org.kde.okular
        - org.mozilla.firefox

  - type: signing
  
